###
# computation config keys
output_dir: ./_computed-notebooks
default_kernel_name: cesm-exp
project: NCGD0011


###
# data sources
data_sources:
    casename: &casename
      smyle-fosi.regional.lat-range-basin.000

###
# book table of contents
book_toc:
  format: jb-book
  root: description
  parts:
    - caption: Ocean Carbon Cycle
      chapters:
        - file: ocn-fgco2
    - caption: Ocean Tracers
      chapters:
        - file: intro-ocn-tracer-views
          sections:
            - glob: ocn-tracer-views*

###
# book _config.yml keys
book_config_keys:
  title: My CESM Experiment
  repository:
    url: https://github.com/matt-long/my-cesm-experiment
    path_to_book: notebooks
    branch: main

###
# computational notebooks
compute_notebooks:  

  description:
    use_cluster: False
    parameter_groups:
      none:
        casename: *casename
  
  ocn-fgco2:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
  
  ocn-tracer-views:
    use_cluster: True
    kernel_name: cesm-exp
    default_params:
      casename: *casename
      component: pop
      stream: h
    parameter_groups:
      temperature:
        variable_id: TEMP
      salinity:
        variable_id: SALT
      oxygen:
        variable_id: O2
